name = "AerialGroundPathFinding"
uuid = "a953f879-f603-4a55-a90d-f6afb9ebeab6"
authors = ["Shushman <shushmanchoudhury@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
